import { generateLeasePdf } from "../../lib/pdfFromText";
export const runtime = "edge";

const DISCLAIMER =
  "This document was generated by AI for informational purposes. It is not a substitute for legal advice. We recommend having this document reviewed by a qualified solicitor or attorney before signing.";

export default async function handler(req: Request) {
  if (req.method !== "POST") return new Response(null, { status: 405 });

  let body: Record<string, unknown> = {};
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid request body." }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const leaseText = String(body.leaseText ?? "").trim();
  const landlordName = String(body.landlordName ?? "").trim();
  const tenantNames = Array.isArray(body.tenantNames)
    ? (body.tenantNames as string[]).map(String)
    : [String(body.tenantNames ?? "")].filter(Boolean);
  const propertyAddress = String(body.propertyAddress ?? "").trim();

  if (!leaseText || !landlordName || tenantNames.length === 0 || !propertyAddress) {
    return new Response(
      JSON.stringify({ error: "Missing leaseText, landlordName, tenantNames, or propertyAddress." }),
      { status: 400, headers: { "Content-Type": "application/json" } }
    );
  }

  try {
    const bytes = await generateLeasePdf({
      title: "Residential Tenancy Agreement",
      landlordName,
      tenantNames,
      propertyAddress,
      bodyText: leaseText,
      disclaimer: DISCLAIMER,
    });
    return new Response(bytes, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="lease.pdf"`,
      },
    });
  } catch (e) {
    console.error(e);
    return new Response(JSON.stringify({ error: "Failed to generate PDF." }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
}
