import { getEnv } from "../../lib/cloudflareEnv";
import { logAiUsage } from "../../lib/aiUsageLog";
import { getAdminClient } from "../../lib/apiAuth";

export const runtime = "edge";

const DISCLAIMER_END =
  "\n\nThis notice was generated by AI. Landlord-tenant law is complex. We strongly recommend review by a qualified solicitor or attorney before serving.";

const SYSTEM_PROMPT = `You are a specialist landlord-tenant solicitor (UK) or real estate attorney (US).
For UK England & Wales: Determine the correct notice type:
- Section 21 (Form 6A): no-fault eviction, 2 months notice, requires protected deposit and documents served.
- Section 8 (Form 3): fault-based. Use correct Schedule 2 grounds. Ground 8 (2+ months arrears) = 2 weeks. Ground 10/11 (some arrears/persistent) = 2 weeks. Ground 12/13/14 (breach/damage/nuisance) = 2 weeks. Ground 1 (owner wants property back) = 2 months.
For UK Scotland: Use correct notice under Private Housing (Tenancies) (Scotland) Act 2016.
For US: Use correct notice type for the specific state:
- Non-payment: Pay or Quit with correct state notice period
- Lease violation: Cure or Quit with correct state notice period
- Serious violation: Unconditional Quit where applicable
Fill in all landlord, tenant, property details. Include all mandatory state language.
Do not add any disclaimer to the document text; a disclaimer will be appended automatically.
Respond with a single JSON object only, no other text, with exactly these keys:
- "noticeType": string (e.g. "Section 8 (Ground 8)", "Section 21", "Pay or Quit (5-day)", "Cure or Quit (10-day)")
- "noticePeriod": string (e.g. "2 weeks", "2 months", "5 days", "14 days")
- "documentText": string (the full notice document text only, no disclaimer)
- "nextSteps": string[] (array of 4-6 short steps: serve notice, wait period, apply to court, hearing, possession order, bailiff if needed)`;

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

export default async function handler(req: Request) {
  if (req.method !== "POST") return new Response(null, { status: 405 });

  const openaiKey = getEnv().OPENAI_API_KEY;
  if (!openaiKey) return json({ error: "Eviction notice generation is not configured." }, 503);

  let body: Record<string, unknown> = {};
  try {
    body = await req.json();
  } catch {
    return json({ error: "Invalid request body." }, 400);
  }

  const userPrompt = buildUserPrompt(body);
  if (!userPrompt) return json({ error: "Missing required answers." }, 400);

  try {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${openaiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: userPrompt },
        ],
        max_tokens: 4000,
        temperature: 0.2,
      }),
    });

    if (!response.ok) {
      const err = await response.text();
      console.error("OpenAI error:", response.status, err);
      return json({ error: "AI service error. Please try again." }, 502);
    }

    const data = (await response.json()) as {
      choices?: { message?: { content?: string } }[];
      usage?: { prompt_tokens?: number; completion_tokens?: number; total_tokens?: number };
    };
    const raw = data.choices?.[0]?.message?.content?.trim();
    if (data.usage) {
      logAiUsage("generate_eviction_notice", "gpt-4o-mini", data.usage);
    }
    if (!raw) return json({ error: "Empty response from AI." }, 502);

    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    const jsonStr = jsonMatch ? jsonMatch[0] : raw;
    let parsed: {
      noticeType?: string;
      noticePeriod?: string;
      documentText?: string;
      nextSteps?: string[];
    };
    try {
      parsed = JSON.parse(jsonStr) as typeof parsed;
    } catch {
      return json({ error: "Could not parse AI response." }, 502);
    }

    const noticeType = String(parsed.noticeType ?? "Eviction notice");
    const noticePeriod = String(parsed.noticePeriod ?? "See document");
    const documentText = String(parsed.documentText ?? "").trim() + DISCLAIMER_END;
    const nextSteps = Array.isArray(parsed.nextSteps) ? parsed.nextSteps : [];

    // Store in generated_documents for potential payment flow
    try {
      const adminClient = getAdminClient();
      await adminClient.from("generated_documents").insert({
        document_type: "eviction_notice",
        document_text: documentText,
        paid: false,
        expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      });
    } catch {
      // Non-fatal: continue even if storage fails
    }

    return json({ noticeType, noticePeriod, documentText, nextSteps });
  } catch (e) {
    console.error(e);
    return json({ error: "Failed to generate eviction notice." }, 500);
  }
}

function buildUserPrompt(body: Record<string, unknown>): string | null {
  const country = String(body.country ?? "").trim();
  const tenancyType = String(body.tenancyType ?? "").trim();
  const state = String(body.state ?? "").trim();
  const reason = String(body.reason ?? "").trim();
  const rentOwed = String(body.rentOwed ?? "").trim();
  const previousNotice = String(body.previousNotice ?? "").trim();
  const previousNoticeType = String(body.previousNoticeType ?? "").trim();
  const previousNoticeWhen = String(body.previousNoticeWhen ?? "").trim();
  const landlordName = String(body.landlordName ?? "").trim();
  const landlordAddress = String(body.landlordAddress ?? "").trim();
  const tenantName = String(body.tenantName ?? "").trim();
  const tenantAddress = String(body.tenantAddress ?? "").trim();
  const propertyAddress = String(body.propertyAddress ?? "").trim();

  if (!country || !reason || !landlordName || !tenantName || !propertyAddress) return null;

  const parts = [
    `Country: ${country}`,
    country === "UK" ? `Tenancy type: ${tenancyType || "N/A"}` : `State: ${state || "N/A"}`,
    `Reason for eviction: ${reason}`,
    rentOwed ? `Rent owed: ${rentOwed}` : "",
    `Previous notice served: ${previousNotice}`,
    previousNotice === "Yes" && (previousNoticeType || previousNoticeWhen)
      ? `Previous notice: ${previousNoticeType} on ${previousNoticeWhen}`
      : "",
    `Landlord: ${landlordName}, ${landlordAddress}`,
    `Tenant: ${tenantName}, ${tenantAddress}`,
    `Property: ${propertyAddress}`,
  ];
  return parts.filter(Boolean).join("\n");
}
