import type { NextApiRequest, NextApiResponse } from "next";
import { generateLeasePdf } from "../../lib/pdfFromText";

export const runtime = "edge";

const DISCLAIMER =
  "This document was generated by AI for informational purposes. It is not a substitute for legal advice. We recommend having this document reviewed by a qualified solicitor or attorney before signing.";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const body = (req.body ?? {}) as Record<string, unknown>;
  const leaseText = String(body.leaseText ?? "").trim();
  const landlordName = String(body.landlordName ?? "").trim();
  const tenantNames = Array.isArray(body.tenantNames) ? (body.tenantNames as string[]).map(String) : [String(body.tenantNames ?? "")].filter(Boolean);
  const propertyAddress = String(body.propertyAddress ?? "").trim();

  if (!leaseText || !landlordName || tenantNames.length === 0 || !propertyAddress) {
    return res.status(400).json({ error: "Missing leaseText, landlordName, tenantNames, or propertyAddress." });
  }

  try {
    const bytes = await generateLeasePdf({
      title: "Residential Tenancy Agreement",
      landlordName,
      tenantNames,
      propertyAddress,
      bodyText: leaseText,
      disclaimer: DISCLAIMER,
    });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", 'attachment; filename="lease.pdf"');
    return res.status(200).send(bytes);
  } catch (e) {
    console.error(e);
    return res.status(500).json({ error: "Failed to generate PDF." });
  }
}
