import { generateNoticePdf } from "../../lib/pdfFromText";
export const runtime = "edge";

const DISCLAIMER =
  "This document was generated by AI for informational purposes. It is not a substitute for legal advice. We recommend having this document reviewed by a qualified solicitor or attorney before use.";

export default async function handler(req: Request) {
  if (req.method !== "POST") return new Response(null, { status: 405 });

  let body: Record<string, unknown> = {};
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid request body." }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const documentText = String(body.documentText ?? "").trim();
  const noticeType = String(body.noticeType ?? "Eviction Notice").trim();
  if (!documentText) {
    return new Response(JSON.stringify({ error: "Missing documentText." }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  try {
    const bytes = await generateNoticePdf({
      title: noticeType,
      bodyText: documentText,
      disclaimer: DISCLAIMER,
    });
    return new Response(bytes, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="eviction-notice.pdf"`,
      },
    });
  } catch (e) {
    console.error(e);
    return new Response(JSON.stringify({ error: "Failed to generate PDF." }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
}
