import type { NextApiRequest, NextApiResponse } from "next";
import { generateNoticePdf } from "../../lib/pdfFromText";

export const runtime = "edge";

const DISCLAIMER =
  "This document was generated by AI for informational purposes. It is not a substitute for legal advice. We recommend having this document reviewed by a qualified solicitor or attorney before use.";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const body = (req.body ?? {}) as Record<string, unknown>;
  const documentText = String(body.documentText ?? "").trim();
  const noticeType = String(body.noticeType ?? "Eviction Notice").trim();

  if (!documentText) return res.status(400).json({ error: "Missing documentText." });

  try {
    const bytes = await generateNoticePdf({
      title: noticeType,
      bodyText: documentText,
      disclaimer: DISCLAIMER,
    });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="eviction-notice.pdf"`);
    return res.status(200).send(bytes);
  } catch (e) {
    console.error(e);
    return res.status(500).json({ error: "Failed to generate PDF." });
  }
}
