import { getRequestContext } from "@cloudflare/next-on-pages";
import { getAdminClient } from "../../lib/apiAuth";

export const runtime = "edge";

const DISCLAIMER =
  "IMPORTANT: This document was generated by AI for informational purposes only. It does not constitute legal advice. We strongly recommend review by a qualified solicitor or attorney before signing.\n\n";

const SYSTEM_PROMPT = `You are a specialist landlord-tenant solicitor (UK) or real estate attorney (US).

For UK England & Wales: Generate an Assured Shorthold Tenancy (AST) compliant with the Housing Act 1988, Tenant Fees Act 2019, and Deregulation Act 2015. Include deposit protection requirements and How to Rent guide reference.

For UK Scotland: Use Private Residential Tenancy format under the Private Housing (Tenancies) (Scotland) Act 2016.

For UK Northern Ireland: Use the appropriate tenancy format for Northern Ireland.

For US: Generate a state-specific residential lease compliant with the given STATE law. Include mandatory disclosures (lead paint if pre-1978, mould, habitability), correct deposit limits, correct landlord entry notice period, and any rent control provisions.

Number all clauses. Mark anything needing legal review with [REVIEW RECOMMENDED].

Start the document with this disclaimer (include it verbatim): "IMPORTANT: This document was generated by AI for informational purposes only. It does not constitute legal advice. We strongly recommend review by a qualified solicitor or attorney before signing."

Output only the lease text, no preamble or commentary.`;

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

function extractClauses(text: string): string[] {
  const parts = text.split(/\n(?=\d+\.\s)/).filter(Boolean);
  const clauses = parts.map((p) => p.trim()).filter(Boolean);
  if (clauses.length > 0) return clauses;
  const byClause = text.split(/\n(?=Clause\s+\d+)/i).filter(Boolean);
  if (byClause.length > 0) return byClause.map((p) => p.trim()).filter(Boolean);
  return [text];
}

export default async function handler(req: Request) {
  if (req.method !== "POST") return new Response(null, { status: 405 });

  let env: Record<string, string> = {};
  try {
    env = getRequestContext().env as Record<string, string>;
  } catch {
    env = process.env as Record<string, string>;
  }

  const openaiKey = env.OPENAI_API_KEY;
  if (!openaiKey) return json({ error: "Lease generation is not configured. Please contact support." }, 503);

  let body: Record<string, unknown> = {};
  try {
    body = await req.json();
  } catch {
    return json({ error: "Invalid request body." }, 400);
  }

  const userPrompt = buildUserPrompt(body);
  if (!userPrompt) return json({ error: "Missing required form data. Please fill in all required fields." }, 400);

  try {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${openaiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: userPrompt },
        ],
        max_tokens: 4000,
        temperature: 0.3,
      }),
    });

    if (!response.ok) {
      const err = await response.text();
      console.error("OpenAI error:", response.status, err);
      return json({ error: "AI service error. Please try again." }, 502);
    }

    const data = (await response.json()) as {
      choices?: { message?: { content?: string } }[];
      usage?: { prompt_tokens?: number; completion_tokens?: number; total_tokens?: number };
    };
    const rawLease = data.choices?.[0]?.message?.content?.trim();
    if (data.usage) {
      const { logAiUsage } = await import("../../../lib/aiUsageLog");
      logAiUsage("generate_lease", "gpt-4o-mini", data.usage);
    }
    if (!rawLease) return json({ error: "Empty response from AI. Please try again." }, 502);

    const fullLeaseText = DISCLAIMER + rawLease;
    const clauses = extractClauses(rawLease);
    const clauseCount = clauses.length;
    const previewClauses = clauses.slice(0, 3).join("\n\n");

    const adminClient = getAdminClient();
    const { data: row, error: insertError } = await adminClient
      .from("lease_download_tokens")
      .insert({
        lease_text: fullLeaseText,
        form_json: body,
      })
      .select("token")
      .single();

    if (insertError || !row?.token) {
      console.error("Insert lease_download_tokens:", insertError);
      return json({ error: "Failed to save lease. Please try again." }, 500);
    }

    return json({
      previewClauses: DISCLAIMER + previewClauses,
      clauseCount,
      token: row.token,
    });
  } catch (e) {
    console.error("generate-lease error:", e);
    return json({ error: "Failed to generate lease. Please try again." }, 500);
  }
}

function buildUserPrompt(body: Record<string, unknown>): string | null {
  const country = String(body.country ?? "").trim();
  const region = String(body.region ?? "").trim();
  const state = String(body.state ?? "").trim();
  const address = String(body.propertyAddress ?? "").trim();
  const propertyType = String(body.propertyType ?? "").trim();
  const furnished = String(body.furnished ?? "").trim();
  const monthlyRent = body.monthlyRent != null ? String(body.monthlyRent) : "";
  const securityDeposit = body.securityDeposit != null ? String(body.securityDeposit) : "";
  const leaseStartDate = String(body.leaseStartDate ?? "").trim();
  const leaseDuration = String(body.leaseDuration ?? "").trim();
  const customMonths = String(body.customMonths ?? "").trim();
  const petsAllowed = String(body.petsAllowed ?? "").trim();
  const smokingAllowed = String(body.smokingAllowed ?? "").trim();
  const landlordName = String(body.landlordName ?? "").trim();
  const landlordAddress = String(body.landlordAddress ?? "").trim();
  const landlordEmail = String(body.landlordEmail ?? "").trim();
  const landlordPhone = String(body.landlordPhone ?? "").trim();
  const tenantNames = Array.isArray(body.tenantNames)
    ? (body.tenantNames as string[])
    : [String(body.tenantNames ?? "")].filter(Boolean);
  const tenantEmails = Array.isArray(body.tenantEmails)
    ? (body.tenantEmails as string[])
    : [String(body.tenantEmail ?? "")].filter(Boolean);
  const specialClauses = String(body.specialClauses ?? "").trim();
  const currency = country === "UK" ? "£" : "$";

  if (!country || !address || !landlordName || tenantNames.length === 0) return null;

  const jurisdiction =
    country === "UK"
      ? `United Kingdom${region ? ` - ${region}` : ""}`
      : `United States - ${state || "N/A"}`;
  const tenants = tenantNames
    .map((t, i) => `Tenant ${i + 1}: ${t}${tenantEmails[i] ? ` (${tenantEmails[i]})` : ""}`)
    .join(", ");
  const duration =
    leaseDuration === "Custom" && customMonths ? `${customMonths} months` : leaseDuration;

  const parts = [
    `Jurisdiction: ${jurisdiction}`,
    `Property: ${address}`,
    `Type: ${propertyType || "N/A"}, Furnished: ${furnished || "N/A"}`,
    `Rent: ${currency}${monthlyRent}/month, Deposit: ${currency}${securityDeposit}`,
    `Lease: ${leaseStartDate} for ${duration}`,
    `Landlord: ${landlordName}, ${landlordAddress}${landlordEmail ? `, ${landlordEmail}` : ""}${landlordPhone ? `, ${landlordPhone}` : ""}`,
    `Tenants: ${tenants}`,
    `Pets: ${petsAllowed || "N/A"}, Smoking: ${smokingAllowed || "N/A"}`,
  ];
  if (specialClauses) parts.push(`Special clauses: ${specialClauses}`);
  return parts.join("\n");
}
