import type { NextApiRequest, NextApiResponse } from "next";
import { getEnv } from "../../lib/cloudflareEnv";

export const runtime = "edge";

const DISCLAIMER_END =
  "\n\nThis notice was generated by AI. Landlord-tenant law is complex. We strongly recommend review by a qualified solicitor or attorney before serving.";

const SYSTEM_PROMPT = `You are a specialist landlord-tenant solicitor (UK) or real estate attorney (US).

For UK England & Wales:
- Section 8 (fault): Use prescribed Form 3. State the correct grounds under Schedule 2 Housing Act 1988 based on the reason given. Use correct notice periods: Ground 8 (2 months arrears) = 2 weeks, Ground 10/11 = 2 weeks, Ground 1 = 2 months.
- Section 21 (no fault): Use prescribed Form 6A. Give 2 months notice. Include mandatory statement about deposit protection and documents served.

For UK Scotland: Use correct notice under Private Housing (Tenancies) (Scotland) Act 2016.

For US: Use correct notice type for the specific state:
- Non-payment: Pay or Quit with correct state notice period
- Lease violation: Cure or Quit with correct state notice period
- Serious violation: Unconditional Quit where applicable
Fill in all landlord, tenant, property details. Include all mandatory state language.

Do not add any disclaimer to the document text; a disclaimer will be appended automatically.

Respond with a single JSON object only, no other text, with exactly these keys:
- "noticeType": string (e.g. "Section 8 (Ground 8)", "Section 21", "Pay or Quit (5-day)", "Cure or Quit (10-day)")
- "noticePeriod": string (e.g. "2 weeks", "2 months", "5 days", "14 days")
- "documentText": string (the full notice document text only, no disclaimer)
- "nextSteps": string[] (array of 4-6 short steps: serve notice, wait period, apply to court, hearing, possession order, bailiff if needed)`;

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const openaiKey = getEnv().OPENAI_API_KEY;
  if (!openaiKey) return res.status(503).json({ error: "Eviction notice generation is not configured." });

  const body = (req.body ?? {}) as Record<string, unknown>;
  const userPrompt = buildUserPrompt(body);
  if (!userPrompt) return res.status(400).json({ error: "Missing required answers." });

  try {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${openaiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: userPrompt },
        ],
        max_tokens: 4000,
        temperature: 0.2,
      }),
    });
    if (!response.ok) {
      const err = await response.text();
      console.error("OpenAI error:", response.status, err);
      return res.status(502).json({ error: "AI service error. Please try again." });
    }
    const data = (await response.json()) as { choices?: { message?: { content?: string } }[] };
    const raw = data.choices?.[0]?.message?.content?.trim();
    if (!raw) return res.status(502).json({ error: "Empty response from AI." });

    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    const jsonStr = jsonMatch ? jsonMatch[0] : raw;
    let parsed: { noticeType?: string; noticePeriod?: string; documentText?: string; nextSteps?: string[] };
    try {
      parsed = JSON.parse(jsonStr) as typeof parsed;
    } catch {
      return res.status(502).json({ error: "Could not parse AI response." });
    }
    const noticeType = String(parsed.noticeType ?? "Eviction notice");
    const noticePeriod = String(parsed.noticePeriod ?? "See document");
    const documentText = String(parsed.documentText ?? "").trim() + DISCLAIMER_END;
    const nextSteps = Array.isArray(parsed.nextSteps) ? parsed.nextSteps : [];

    return res.status(200).json({
      noticeType,
      noticePeriod,
      documentText,
      nextSteps,
    });
  } catch (e) {
    console.error(e);
    return res.status(500).json({ error: "Failed to generate eviction notice." });
  }
}

function buildUserPrompt(body: Record<string, unknown>): string | null {
  const country = String(body.country ?? "").trim();
  const tenancyType = String(body.tenancyType ?? "").trim();
  const state = String(body.state ?? "").trim();
  const reason = String(body.reason ?? "").trim();
  const rentOwed = String(body.rentOwed ?? "").trim();
  const previousNotice = String(body.previousNotice ?? "").trim();
  const previousNoticeType = String(body.previousNoticeType ?? "").trim();
  const previousNoticeWhen = String(body.previousNoticeWhen ?? "").trim();
  const landlordName = String(body.landlordName ?? "").trim();
  const landlordAddress = String(body.landlordAddress ?? "").trim();
  const tenantName = String(body.tenantName ?? "").trim();
  const tenantAddress = String(body.tenantAddress ?? "").trim();
  const propertyAddress = String(body.propertyAddress ?? "").trim();

  if (!country || !reason || !landlordName || !tenantName || !propertyAddress) return null;

  const parts = [
    `Country: ${country}`,
    country === "UK" ? `Tenancy type: ${tenancyType || "N/A"}` : `State: ${state || "N/A"}`,
    `Reason for eviction: ${reason}`,
    rentOwed ? `Rent owed: ${rentOwed}` : "",
    `Previous notice served: ${previousNotice}`,
    previousNotice === "Yes" && (previousNoticeType || previousNoticeWhen)
      ? `Previous notice: ${previousNoticeType} on ${previousNoticeWhen}`
      : "",
    `Landlord: ${landlordName}, ${landlordAddress}`,
    `Tenant: ${tenantName}, ${tenantAddress}`,
    `Property: ${propertyAddress}`,
  ];
  return parts.filter(Boolean).join("\n");
}
