import { getRequestContext } from "@cloudflare/next-on-pages";
export const runtime = "edge";

const SYSTEM_PROMPT = `You are a friendly property law assistant helping landlords generate legal documents. Your job is to:
1. DETECT what document they need from their description:
   - Lease/tenancy agreement → collect: jurisdiction, address, property type, rent, deposit, start date, duration, landlord name/address, tenant name(s), furnished status, pets, smoking
   - Section 8 notice (UK, fault-based eviction) → collect: jurisdiction (must be England & Wales), reason (rent arrears/behaviour/damage), months of arrears if applicable, landlord name/address, tenant name/address, property address, tenancy start date
   - Section 21 notice (UK, no-fault eviction) → collect: landlord name/address, tenant name/address, property address, tenancy start date, confirm deposit protected and documents served
   - Pay or Quit / eviction notice (US) → collect: state, reason, landlord name/address, tenant name/address, property address, amount owed if applicable
   - Rent increase letter → collect: jurisdiction, landlord/tenant details, current rent, new rent, effective date, notice period
2. ASK ONE QUESTION AT A TIME. Never ask multiple questions in one message. Be conversational and friendly.
3. When you have all required information, respond with EXACTLY this JSON (no other text before or after):
{"ready":true,"documentType":"ast_lease"|"section_8"|"section_21"|"pay_or_quit"|"cure_or_quit"|"rent_increase","jurisdiction":"england_wales"|"scotland"|"northern_ireland"|"us_XX","data":{...}}
Use documentType: ast_lease, section_8, section_21, pay_or_quit, cure_or_quit, rent_increase. Use jurisdiction: england_wales, scotland, northern_ireland, or us_[state_code] for US. Put ALL collected fields (address, landlordName, tenantName, rent, etc.) in the data object.
4. Keep messages SHORT. Maximum 2 sentences per response. Plain English only — no legal jargon.
5. If they seem confused or stuck, offer an example of what to type.
6. Never ask for information they already provided. Never ask more than 6-8 questions total.`;

const DOCUMENT_GEN_PROMPT = `You are a specialist landlord-tenant solicitor (UK) or real estate attorney (US). Generate the complete, legally accurate document based on the type and jurisdiction below. Use correct forms and mandatory wording:
- ast_lease (England & Wales): AST compliant with Housing Act 1988, Tenant Fees Act 2019, Deregulation Act 2015; deposit protection and How to Rent reference. Scotland: PRT under 2016 Act. Northern Ireland: appropriate format. US: state-specific lease with mandatory disclosures.
- section_8: Prescribed Form 3, correct Schedule 2 grounds and notice periods (e.g. Ground 8 = 2 weeks, Ground 10/11 = 2 weeks).
- section_21: Prescribed Form 6A, 2 months notice, deposit protection statement.
- pay_or_quit / cure_or_quit: State-specific notice with correct notice period and mandatory language.
- rent_increase: Correct notice format for jurisdiction.
Start with: "IMPORTANT: This document was generated by AI for informational purposes only. It does not constitute legal advice. We strongly recommend review by a qualified solicitor or attorney before use."
Output ONLY the full document text. No preamble or explanation.`;

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

export default async function handler(req: Request) {
  if (req.method !== "POST") return new Response(null, { status: 405 });

  let env: Record<string, string> = {};
  try {
    env = getRequestContext().env as Record<string, string>;
  } catch {
    env = process.env as Record<string, string>;
  }

  const openaiKey = env.OPENAI_API_KEY;
  if (!openaiKey) return json({ error: "Service not configured." }, 503);

  let body: { messages?: Array<{ role: string; content: string }>; sessionId?: string } = {};
  try {
    body = await req.json();
  } catch {
    return json({ error: "Invalid request body." }, 400);
  }

  const messages = body.messages;
  if (!Array.isArray(messages) || messages.length === 0) {
    return json({ error: "Send a messages array with at least one message." }, 400);
  }

  const formatted = messages
    .map((m) => ({
      role: m.role === "assistant" ? ("assistant" as const) : ("user" as const),
      content: String(m.content ?? "").trim(),
    }))
    .filter((m) => m.content.length > 0);

  if (formatted.length === 0) return json({ error: "No valid messages." }, 400);

  try {
    const chatRes = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${openaiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [{ role: "system", content: SYSTEM_PROMPT }, ...formatted],
        max_tokens: 500,
        temperature: 0.3,
      }),
    });

    if (!chatRes.ok) {
      const err = await chatRes.text();
      console.error("OpenAI chat error:", chatRes.status, err);
      return json({ error: "Something went wrong. Please try again." }, 502);
    }

    const chatData = (await chatRes.json()) as { choices?: { message?: { content?: string } }[] };
    const content = chatData.choices?.[0]?.message?.content?.trim() ?? "";
    if (!content) return json({ error: "Empty response." }, 502);

    let parsed: {
      ready?: boolean;
      documentType?: string;
      jurisdiction?: string;
      data?: Record<string, unknown>;
    } | null = null;

    try {
      const start = content.indexOf("{");
      const end = content.lastIndexOf("}");
      if (start !== -1 && end > start) {
        parsed = JSON.parse(content.slice(start, end + 1)) as typeof parsed;
      }
    } catch {
      /* not JSON — it's a follow-up question */
    }

    if (!parsed?.ready || !parsed.documentType) {
      return json({ message: content, ready: false });
    }

    const genRes = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${openaiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          { role: "system", content: DOCUMENT_GEN_PROMPT },
          {
            role: "user",
            content: `documentType: ${parsed.documentType}\njurisdiction: ${parsed.jurisdiction ?? "unknown"}\ndata: ${JSON.stringify(parsed.data ?? {})}`,
          },
        ],
        max_tokens: 4000,
        temperature: 0.3,
      }),
    });

    if (!genRes.ok) {
      const err = await genRes.text();
      console.error("OpenAI doc gen error:", genRes.status, err);
      return json({ error: "Failed to generate document. Please try again." }, 502);
    }

    const genData = (await genRes.json()) as { choices?: { message?: { content?: string } }[] };
    const documentText = genData.choices?.[0]?.message?.content?.trim() ?? "";
    if (!documentText) return json({ error: "Empty document." }, 502);

    const docLabel =
      parsed.documentType === "ast_lease" || parsed.documentType === "rent_increase"
        ? "lease"
        : "eviction notice";

    return json({
      message: null,
      ready: true,
      documentType: parsed.documentType,
      jurisdiction: parsed.jurisdiction,
      data: parsed.data,
      documentText,
      documentLabel: docLabel,
    });
  } catch (e) {
    console.error(e);
    return json({ error: "Something went wrong. Please try again." }, 500);
  }
}
