import { getRequestContext } from "@cloudflare/next-on-pages";
import { getAdminClient } from "../../lib/apiAuth";

export const runtime = "edge";

type Req = Request & { body?: unknown; method?: string };
export default async function handler(req: Req) {
  const method = req.method ?? (req as Request).method;
  if (method !== "POST") return new Response(null, { status: 405 });

  let body: { documentType?: string; jurisdiction?: string; data?: Record<string, unknown> };
  try {
    if (typeof (req as Request).json === "function") {
      body = await (req as Request).json();
    } else {
      body = ((req as { body?: unknown }).body ?? {}) as typeof body;
    }
  } catch {
    return new Response(JSON.stringify({ error: "Invalid JSON." }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const { documentType, jurisdiction, data } = body;
  if (!documentType || !data || typeof data !== "object") {
    return new Response(
      JSON.stringify({ error: "documentType and data are required." }),
      { status: 400, headers: { "Content-Type": "application/json" } }
    );
  }

  const env = getRequestContext().env as Record<string, string>;
  const openaiKey = env.OPENAI_API_KEY;
  if (!openaiKey) {
    return new Response(JSON.stringify({ error: "Service not configured." }), {
      status: 503,
      headers: { "Content-Type": "application/json" },
    });
  }

  const systemPrompts: Record<string, string> = {
    ast_lease: `You are a specialist landlord-tenant solicitor. Generate a complete Assured Shorthold Tenancy agreement compliant with the Housing Act 1988, Tenant Fees Act 2019, and Deregulation Act 2015. Number all clauses. Include deposit protection requirements, How to Rent guide reference, and all standard AST clauses. Mark anything needing legal review with [REVIEW]. Start with: "IMPORTANT: Generated by AI for informational purposes only. Not legal advice. Have this reviewed by a solicitor before signing."`,
    section_8: `You are a specialist landlord-tenant solicitor. Generate a Section 8 Notice to Quit using the prescribed Form 3 under the Housing Act 1988. Use the correct grounds based on the reason provided. Include correct notice periods. Fill in all landlord, tenant, and property details. Start with: "IMPORTANT: Generated by AI for informational purposes only. Not legal advice. Have this reviewed by a solicitor before serving."`,
    section_21: `You are a specialist landlord-tenant solicitor. Generate a Section 21 Notice using the prescribed Form 6A. Give 2 months notice. Include all mandatory statements. Fill in all details. Start with: "IMPORTANT: Generated by AI for informational purposes only. Not legal advice. Have this reviewed by a solicitor before serving."`,
    pay_or_quit: `You are a real estate attorney. Generate a Pay or Quit notice compliant with the laws of the specified US state. Use the correct notice period for that state. Fill in all details. Start with: "IMPORTANT: Generated by AI for informational purposes only. Not legal advice. Have this reviewed by an attorney before serving."`,
    cure_or_quit: `You are a real estate attorney. Generate a Cure or Quit notice compliant with the laws of the specified US state. Use the correct notice period for that state. Fill in all details. Start with: "IMPORTANT: Generated by AI for informational purposes only. Not legal advice. Have this reviewed by an attorney before serving."`,
    rent_increase: `You are a specialist landlord-tenant solicitor (UK) or real estate attorney (US). Generate a rent increase notice compliant with the jurisdiction. Include current rent, new rent, effective date, and required notice period. Start with: "IMPORTANT: Generated by AI for informational purposes only. Not legal advice. Have this reviewed by a solicitor or attorney before serving."`,
  };

  const systemPrompt = systemPrompts[documentType] ?? systemPrompts.ast_lease;
  const userPrompt = `Generate the document using these details: ${JSON.stringify(data, null, 2)}`;

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${openaiKey}`,
    },
    body: JSON.stringify({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      max_tokens: 4000,
      temperature: 0.1,
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    console.error("OpenAI error:", response.status, err);
    return new Response(
      JSON.stringify({ error: "Failed to generate document." }),
      { status: 502, headers: { "Content-Type": "application/json" } }
    );
  }

  const result = (await response.json()) as { choices?: { message?: { content?: string } }[] };
  const documentText = result.choices?.[0]?.message?.content?.trim() ?? "";
  if (!documentText) {
    return new Response(JSON.stringify({ error: "Empty document." }), {
      status: 502,
      headers: { "Content-Type": "application/json" },
    });
  }

  const adminClient = getAdminClient();
  const docId = crypto.randomUUID();
  const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();

  const { error: insertError } = await adminClient.from("generated_documents").insert({
    id: docId,
    document_type: documentType,
    jurisdiction: jurisdiction ?? null,
    document_text: documentText,
    paid: false,
    expires_at: expiresAt,
  });

  if (insertError) {
    console.error("generated_documents insert:", insertError);
    return new Response(JSON.stringify({ error: "Failed to store document." }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }

  const sections = documentText.split("\n\n");
  const preview = sections.slice(0, 3).join("\n\n");

  return new Response(
    JSON.stringify({
      documentId: docId,
      preview,
      documentType,
      fullLength: documentText.length,
    }),
    { headers: { "Content-Type": "application/json" } }
  );
}
